version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    image: reducto:latest
    volumes:
#      - .:/go/src/reducto
      - go_modules:/go/pkg/mod
    environment:
      REDUCTO_CONFIG_PATH: './docker-config.yml.sample'
    command: ["./wait-for", "postgres:5432", "--", "./server"]

  keygen:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    image: reducto:latest
    volumes:
      - go_modules:/go/pkg/mod
    environment:
      REDUCTO_CONFIG_PATH: './docker-config.yml.sample'
    command: ["./wait-for", "postgres:5432", "--", "./keygen"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reducto
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  db_data:
  go_modules: